### ISSUE TITLE
Testing Bug: text file of class does not exist

### ISSUE THREAD

**Issue by ash1995** [avanetten/simrdwn#20]
During the testing phase, the program halts due to the absence of a file named **building.txt** which is the text file containing detections of my class (building). However, it doesn't appear to have been generated during testing phase and I'm unsure as to why. 

```
Loading weights from /raid/local/src/simrdwn/results/train_yolt_dense_buildings_2019_01_16_07-05-19/ave_dense_20000_tmp.weights...label i: 0, tmp0
label i: 1, building
Done!
Learning Rate: 0.0001, Momentum: 0.9, Decay: 0.0005
valid_list_loc: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/valid_splitims_input_files.txt
Output file: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/tmp0.txt

Total Detection Time: 22.91982 Seconds
Length of time to run command:  ./yolt/darknet -i 0 yolt2 valid /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/logs/ave_dense.cfg /raid/local/src/simrdwn/results/train_yolt_dense_buildings_2019_01_16_07-05-19/ave_dense_20000_tmp.weights null 0 0.0 null /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09 /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/valid_splitims_input_files.txt tmp0,building 2 3 /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/logs/yolt_loss.txt 0.15  2>&1 | tee -a /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/logs/valid_yolt_dense_buildings_2019_01_17_13-31-09.log for 0 cutouts: 25.2416059971 seconds
"
valid_file: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/tmp0.txt
Augmenting dataframe of initial length: 2 ...
removing bad idxs: [0, 1]
Time to augment dataframe of length: 0 = 0.0165009498596 seconds
valid_file: /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/building.txt
Traceback (most recent call last):
  File "simrdwn/core/simrdwn.py", line 1953, in <module>
    main()
  File "simrdwn/core/simrdwn.py", line 1945, in main
    execute(args)
  File "simrdwn/core/simrdwn.py", line 1475, in execute
    rotate_boxes=args.rotate_boxes)
  File "simrdwn/core/simrdwn.py", line 1022, in run_valid
    rotate_boxes=rotate_boxes)
  File "/raid/local/src/simrdwn/core/post_process.py", line 291, in post_process_yolt_valid_create_df
    'Ymax'])
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /raid/local/src/simrdwn/results/valid_yolt_dense_buildings_2019_01_17_13-31-09/building.txt does not exist
```

**Comment by avanetten** [comment]
In the test phase you need to tell SIMRDWN which trained weight file to use for inference. In your case, you are telling it to load a weight file that does not exist, hence the error.
