### ISSUE TITLE
FASTER_RCNN: TypeError: sequence item 0: expected string, int found

### ISSUE THREAD

**Issue by archenroot** [avanetten/simrdwn#28]
```
root@83d06eb5eb3c:/raid/simrdwn/data# python /raid/simrdwn/core/simrdwn.py --framework faster_rcnn --mode train --outname resnet101_3class_vehicles --label_map_path /simrdwn/data/class_labels_airplane_boat_car.pbtxt --tf_cfg_train_file /raid/simrdwn/configs/faster_rcnn_resnet101_simrdwn.config --train_tf_record /raid/simrdwn/data/labels_airplane_boat_car_train.tfrecord --max_batches 30000 --batch_size 16 --gpu 0

Permit me to introduce myself...
Well, I’m glad we got that out of the way.

Traceback (most recent call last):
  File "/raid/simrdwn/core/simrdwn.py", line 1955, in <module>
    main()
  File "/raid/simrdwn/core/simrdwn.py", line 1946, in main
    args = update_args(args)
  File "/raid/simrdwn/core/simrdwn.py", line 114, in update_args
    args.yolt_object_labels_str = ','.join(args.yolt_object_labels)
TypeError: sequence item 0: expected string, int found
```

**Comment by archenroot** [comment]
Ok, its just issue with path of input files/folders...
