### ISSUE TITLE
When I run the test command, I got an error

### ISSUE THREAD

**Issue by maiff** [avanetten/simrdwn#36]
```
Creating args.inference_graph_path_tot: /simrdwn/results/train_yolt2_dense_3class_vehicles_2019_05_05_06-30-19/frozen_model/frozen_inference_graph.pb ...
Removing /simrdwn/results/train_yolt2_dense_3class_vehicles_2019_05_05_06-30-19/frozen_model/saved_model so we can overwrite it...
/simrdwn/results/train_yolt2_dense_3class_vehicles_2019_05_05_06-30-19
Traceback (most recent call last):
  File "/simrdwn/core/simrdwn.py", line 2234, in <module>
    main()
  File "/simrdwn/core/simrdwn.py", line 2226, in main
    execute(args)
  File "/simrdwn/core/simrdwn.py", line 1660, in execute
    tf_cfg_train_file=args.tf_cfg_train_file)
  File "/simrdwn/core/simrdwn.py", line 588, in tf_export_model_cmd
    num_max_tmp = np.max(nums_tmp)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2505, in amax
    initial=initial)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

In simrdwn.py
in 588 line
```
checkpoints_tmp = [ftmp for ftmp in os.listdir(trained_dir)
            if ftmp.startswith('model.ckpt')]
    #  print ("checkpoints tmp:", checkpoints_tmp)
    nums_tmp = [int(z.split('model.ckpt-')[-1].split('.')[0]) for z in checkpoints_tmp]
    #  print ("nums_tmp:", nums_tmp)
    num_max_tmp = np.max(nums_tmp)
```
then  I found there is not model.ckpt file.
In the dictionary, it only contains those files:
```
ave_dense_10000_tmp.weights  ave_dense_20000_tmp.weights  ave_dense_5000_tmp.weights
ave_dense_1000_tmp.weights   ave_dense_25000_tmp.weights  ave_dense_final.weights
ave_dense_15000_tmp.weights  ave_dense_30000_tmp.weights  logs
```
what should i do?

**Comment by maiff** [comment]
I solve this problem by change the `yolo` to `yolo2`, but I think my loss is wrong
[![Esz8zj.md.png](https://s2.ax1x.com/2019/05/07/Esz8zj.md.png)](https://imgchr.com/i/Esz8zj)
why did I get this loss?

**Comment by avanetten** [comment]
The original problem is caused by mixing commands to both TensorFlow and YOLT2/3.  As to your loss plot, why do you think that this is wrong?

**Comment by maiff** [comment]
Thanks so much. At first, I think my loss should be like the loss in the README.
