### ISSUE TITLE
Getting an error when try to parse cowc dataset

### ISSUE THREAD

**Issue by Jakaria08** [avanetten/simrdwn#5]
The Error:
Executing get_gdf_tot_cowc()...
0 label_image_path: /home/hipstudents/cosmiq/cowc/datasets/ground_truth_sets/Utah_AGRC/12TVL240120_Annotated_Cars.png
0 image_path: /home/hipstudents/cosmiq/cowc/datasets/ground_truth_sets/Utah_AGRC/12TVL240120.png
Traceback (most recent call last):
  File "parse_cowc.py", line 290, in <module>
    main()
  File "parse_cowc.py", line 273, in main
    verbose=verbose)
  File "parse_cowc.py", line 212, in get_gdf_tot_cowc
    yolt_box_size, verbose=verbose)
  File "parse_cowc.py", line 157, in cowc_to_gdf
    verbose=verbose)
  File "parse_cowc.py", line 78, in gt_boxes_from_cowc_png
    if len(label_locs) == 0:
TypeError: object of type 'zip' has no len()
........................................................

I don't know why this is happening.
I downloaded all data under Utah_AGRC Folder.

**Comment by Jakaria08** [comment]
I solved the problem. 

Instead of -  label_locs = zip(*np.where(gt_c > 0)) 
I use -  label_locs = list(zip(*np.where(gt_c > 0)))
