### ISSUE TITLE
Not finding the tfrecords during test

### ISSUE THREAD

**Issue by jacquesmats** [avanetten/simrdwn#55]
I'm running the following command, which is the same on Readme:

```
# SSD vehicle search
python /simrdwn/simrdwn/core/simrdwn.py \
	--framework ssd \
	--mode test \
	--outname inception_v2_cowc \
	--label_map_path /simrdwn/data/train_data/class_labels_car.pbtxt \
	--train_model_path /simrdwn/results/train_ssd_inception_v2_cowc_mat_2019_07_11_18-16-18 \
	--tf_cfg_train_file ssd_inception_v2_simrdwn.config \
	--use_tfrecords=1 \
	--testims_dir /simrdwn/data/test_images/cowc/Utah_AGRC  \
	--keep_test_slices 0 \
	--test_slice_sep __ \
	--test_make_legend_and_title 0 \
	--edge_buffer_test 1 \
	--test_box_rescale_frac 1 \
	--plot_thresh_str 0.2 \
	--slice_sizes_str 416 \
	--slice_overlap 0.2 \
	--alpha_scaling 1 \
	--show_labels 0
```

And receiving the following error:
```
Traceback (most recent call last):
  File "/simrdwn/simrdwn/core/infer_detections.py", line 312, in <module>
    tf.app.run()
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/simrdwn/simrdwn/core/infer_detections.py", line 137, in main
    input_tfrecord_paths)
  File "/tensorflow/models/research/object_detection/inference/detection_inference.py", line 35, in build_input
    tfrecord_paths, shuffle=False, num_epochs=1)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 259, in string_input_producer
    raise ValueError(not_null_err)
```
I'm having dificulties tracking it down. It seems some path is wrong :thinking:

**Comment by avanetten** [comment]
Have you tried running Line 21 of the dockerfile when in the docker image?

# once started run:
export PYTHONPATH=$PYTHONPATH:/tensorflow/models/research/:/tensorflow/models/research/slim

**Comment by jacquesmats** [comment]
Yes, still not working. Same error /cry

**Comment by avanetten** [comment]
What's in the directory? 	
--train_model_path /simrdwn/results/train_ssd_inception_v2_cowc_mat_2019_07_11_18-16-18

**Comment by jacquesmats** [comment]
![image](https://user-images.githubusercontent.com/20168631/61460725-bb328a80-a945-11e9-976e-03a8d3b4fde6.png)

**Comment by avanetten** [comment]
The most recent push should solve this problem.
