### ISSUE TITLE
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.

### ISSUE THREAD

**Issue by mas-dse-mqh001** [avanetten/simrdwn#76]
Does anyone know what I should do with this error?  Or did I do something wrong?
Thanks a bunch.
===
COMMAND:
(sim_env) root@0caeffcae413:/# python ./simrdwn/simrdwn/core/simrdwn.py --framework ssd --mode train         --testims_dir cowc --outname inception_v2_cowc --label_map_path class_labels_car.pbtxt --tf_cfg_train_file _altered_v0/ssd_inception_v2_simrdwn.config --train_tf_record ./data/cowc_labels_car_train.tfrecord --max_batches 30000 --batch_size 16

ERROR:
--
Well, I'm glad we got that out of the way.

(sim_env) root@0caeffcae413:/# 
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "/tensorflow/models/research/object_detection/model_main.py", line 109, in <module>
    tf.app.run()
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tensorflow/models/research/object_detection/model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/model_lib.py", line 566, in create_estimator_and_inputs
    config_override=config_override)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/utils/config_util.py", line 96, in get_configs_from_pipeline_file
    text_format.Merge(proto_str, pipeline_config)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 685, in Merge
    allow_unknown_field=allow_unknown_field)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 752, in MergeLines
    return parser.MergeLines(lines, message)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 777, in MergeLines
    self._ParseOrMerge(lines, message)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 799, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 891, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.TrainEvalPipelineConfig" has no field named "f".

**Comment by mas-dse-mqh001** [comment]
Fixed: File "/opt/conda/envs/sim_env/lib/python3.6/site-packages/google/protobuf/text_format.py", line 891, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 1:1 : Message type "object_detection.protos.TrainEvalPipelineConfig" has no field named "f".

Yea, I accidentally got "f" in the beginning of tensorflow config file

**Comment by ISS88** [comment]
hello so here I try to train a model of mask r cnn on my own give with the command
python D:\Projet\CV-CommonTools\model_main.py /
--model_dir training /
--pipeline_config_path training\mask_rcnn_inception_v2.config /
--num_train_steps 60000 /
--sample_1_of_n_eval_examples=0 /
--alsologtostderr

but i get the following error


```
Traceback (most recent call last):
  File "D:\Projet\model_main.py", line 110, in <module>
    tf.app.run()
  File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "D:\Projet\model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'

```


could someone guided me please

**Comment by 007Nick700** [comment]
> hello so here I try to train a model of mask r cnn on my own give with the command
> python D:\Projet\CV-CommonTools\model_main.py /
> --model_dir training /
> --pipeline_config_path training\mask_rcnn_inception_v2.config /
> --num_train_steps 60000 /
> --sample_1_of_n_eval_examples=0 /
> --alsologtostderr
> 
> but i get the following error
> 
> ```
> Traceback (most recent call last):
>   File "D:\Projet\model_main.py", line 110, in <module>
>     tf.app.run()
>   File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 299, in run
>     _run_main(main, args)
>   File "C:\Users\Ibrahim\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "D:\Projet\model_main.py", line 71, in main
>     FLAGS.sample_1_of_n_eval_on_train_examples))
> TypeError: create_estimator_and_inputs() missing 1 required positional argument: 'hparams'
> ```
> 
> could someone guided me please

I also run into this error. Did you manage to fix it?

**Comment by codeperfectplus** [comment]
I am getting the same error. Trying with tf-nightly can solve problen

**Comment by vinavajna** [comment]
I am getting the same error.

**Comment by MathewsJosh** [comment]
I am stuck in this error too :(
