### ISSUE TITLE
Add_Geo_Coords

### ISSUE THREAD

**Issue by aghand0ur** [avanetten/simrdwn#86]
Hello,
I am receiving the following error.
I was able to bypass it by setting the following argument as false:
`--test_add_geo_coords 0`

Any clues?
Ali

`Traceback (most recent call last):
  File "/simrdwn/simrdwn/core/simrdwn.py", line 1936, in <module>
    main()
  File "/simrdwn/simrdwn/core/simrdwn.py", line 1928, in main
    execute(args, train_cmd1, test_cmd_tot, test_cmd_tot2)
  File "/simrdwn/simrdwn/core/simrdwn.py", line 1540, in execute
    test_add_geo_coords=args.test_add_geo_coords)
  File "/simrdwn/simrdwn/core/simrdwn.py", line 1130, in run_test
    outProj_str='epsg:3857', verbose=verbose)
  File "/simrdwn/simrdwn/core/add_geo_coords.py", line 211, in add_geo_coords_to_df
    verbose=verbose)
  File "/simrdwn/simrdwn/core/add_geo_coords.py", line 139, in get_row_geo_coords
    x0_wmp, y0_wmp = pyproj.transform(inProj, outProj, lon0, lat0)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pyproj/__init__.py", line 527, in transform
    _proj._transform(p1,p2,inx,iny,inz,radians)
  File "_proj.pyx", line 450, in _proj._transform
RuntimeError: b'latitude or longitude exceeded limits'
`

**Comment by avanetten** [comment]
If your test data is not in geotiff format then test_add_geo_coords should be false.  I'm guessing that your input images are in png or jpg format, which means that there's no sense in trying to add geo coords.

**Comment by avanetten** [comment]
Closing due to lack of activity
