### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yunxiaozimeng** [avanetten/simrdwn#97]
When I finish my train and want to inference images,I met an error that I can not solve .who can help me 

HERE IS ERROR CODES
darknet: ./src/parser.c:312: parse_yolo: Assertion `l.outputs == params.inputs' failed.
label i: 0, grape
Aborted (core dumped)

Length of time to run command:  ./yolt3/darknet -i 0 yolt3 valid /simrdwn/yolt3/cfg/yolov3.cfg /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights null 0 0.0 null /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/test_splitims_input_files.txt grape 1 3 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/yolt_loss.txt 0.025 1  2>&1 | tee -a /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/test_yolt3_dense_cowc_2020_10_17_03-19-04.log for 0 cutouts: 3.5131266117095947 seconds

test_file: /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt
Traceback (most recent call last):
  File "./simrdwn/core/simrdwn.py", line 1949, in <module>
    main()
  File "./simrdwn/core/simrdwn.py", line 1941, in main
    execute(args, train_cmd1, test_cmd_tot, test_cmd_tot2)
  File "./simrdwn/core/simrdwn.py", line 1548, in execute
    test_add_geo_coords=args.test_add_geo_coords)
  File "./simrdwn/core/simrdwn.py", line 1124, in run_test
    rotate_boxes=rotate_boxes)
  File "/simrdwn/simrdwn/core/post_process.py", line 380, in post_process_yolt_test_create_df
    'Ymax'])
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt does not exist: '/simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt'

COMMAND IS HERE
(simrdwn2) root@80eef1fa544e:/simrdwn# python ./simrdwn/core/simrdwn.py --framework yolt3 --mode test --outname dense_cowc --label_map_path /simrdwn/data/class_labels_car.pbtxt --weight_file /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights --yolt_cfg_file /simrdwn/yolt3/cfg/yolov3.cfg --testims_dir /simrdwn/data  --keep_test_slices 0 --test_slice_sep __ --test_make_legend_and_title 0 --edge_buffer_test 1 --test_box_rescale_frac 1 --plot_thresh_str 0.2 --slice_sizes_str 416 --slice_overlap 0.2 --alpha_scaling 1 --show_labels 1 --boxes_per_grid 9

**Comment by sunyuxiu** [comment]
> When I finish my train and want to inference images,I met an error that I can not solve .who can help me
> 
> HERE IS ERROR CODES
> darknet: ./src/parser.c:312: parse_yolo: Assertion `l.outputs == params.inputs' failed.
> label i: 0, grape
> Aborted (core dumped)
> 
> Length of time to run command: ./yolt3/darknet -i 0 yolt3 valid /simrdwn/yolt3/cfg/yolov3.cfg /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights null 0 0.0 null /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/test_splitims_input_files.txt grape 1 3 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/yolt_loss.txt 0.025 1 2>&1 | tee -a /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/test_yolt3_dense_cowc_2020_10_17_03-19-04.log for 0 cutouts: 3.5131266117095947 seconds
> 
> test_file: /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt
> Traceback (most recent call last):
> File "./simrdwn/core/simrdwn.py", line 1949, in
> main()
> File "./simrdwn/core/simrdwn.py", line 1941, in main
> execute(args, train_cmd1, test_cmd_tot, test_cmd_tot2)
> File "./simrdwn/core/simrdwn.py", line 1548, in execute
> test_add_geo_coords=args.test_add_geo_coords)
> File "./simrdwn/core/simrdwn.py", line 1124, in run_test
> rotate_boxes=rotate_boxes)
> File "/simrdwn/simrdwn/core/post_process.py", line 380, in post_process_yolt_test_create_df
> 'Ymax'])
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
> return _read(filepath_or_buffer, kwds)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
> parser = TextFileReader(fp_or_buf, **kwds)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in **init**
> self._make_engine(self.engine)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
> self._engine = CParserWrapper(self.f, **self.options)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in **init**
> self._reader = parsers.TextReader(src, **kwds)
> File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.**cinit**
> File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
> FileNotFoundError: [Errno 2] File /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt does not exist: '/simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt'
> 
> COMMAND IS HERE
> (simrdwn2) root@80eef1fa544e:/simrdwn# python ./simrdwn/core/simrdwn.py --framework yolt3 --mode test --outname dense_cowc --label_map_path /simrdwn/data/class_labels_car.pbtxt --weight_file /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights --yolt_cfg_file /simrdwn/yolt3/cfg/yolov3.cfg --testims_dir /simrdwn/data --keep_test_slices 0 --test_slice_sep __ --test_make_legend_and_title 0 --edge_buffer_test 1 --test_box_rescale_frac 1 --plot_thresh_str 0.2 --slice_sizes_str 416 --slice_overlap 0.2 --alpha_scaling 1 --show_labels 1 --boxes_per_grid 9

I had met the same question as you.Do you solve the problem?
I am looking forward to your reply!

**Comment by sunyuxiu** [comment]
> When I finish my train and want to inference images,I met an error that I can not solve .who can help me
> 
> HERE IS ERROR CODES
> darknet: ./src/parser.c:312: parse_yolo: Assertion `l.outputs == params.inputs' failed.
> label i: 0, grape
> Aborted (core dumped)
> 
> Length of time to run command: ./yolt3/darknet -i 0 yolt3 valid /simrdwn/yolt3/cfg/yolov3.cfg /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights null 0 0.0 null /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/test_splitims_input_files.txt grape 1 3 /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/yolt_loss.txt 0.025 1 2>&1 | tee -a /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/logs/test_yolt3_dense_cowc_2020_10_17_03-19-04.log for 0 cutouts: 3.5131266117095947 seconds
> 
> test_file: /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt
> Traceback (most recent call last):
> File "./simrdwn/core/simrdwn.py", line 1949, in
> main()
> File "./simrdwn/core/simrdwn.py", line 1941, in main
> execute(args, train_cmd1, test_cmd_tot, test_cmd_tot2)
> File "./simrdwn/core/simrdwn.py", line 1548, in execute
> test_add_geo_coords=args.test_add_geo_coords)
> File "./simrdwn/core/simrdwn.py", line 1124, in run_test
> rotate_boxes=rotate_boxes)
> File "/simrdwn/simrdwn/core/post_process.py", line 380, in post_process_yolt_test_create_df
> 'Ymax'])
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
> return _read(filepath_or_buffer, kwds)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
> parser = TextFileReader(fp_or_buf, **kwds)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in **init**
> self._make_engine(self.engine)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
> self._engine = CParserWrapper(self.f, **self.options)
> File "/opt/conda/envs/simrdwn2/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in **init**
> self._reader = parsers.TextReader(src, **kwds)
> File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.**cinit**
> File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
> FileNotFoundError: [Errno 2] File /simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt does not exist: '/simrdwn/results/test_yolt3_dense_cowc_2020_10_17_03-19-04/grape.txt'
> 
> COMMAND IS HERE
> (simrdwn2) root@80eef1fa544e:/simrdwn# python ./simrdwn/core/simrdwn.py --framework yolt3 --mode test --outname dense_cowc --label_map_path /simrdwn/data/class_labels_car.pbtxt --weight_file /simrdwn/results/train_yolt3_dense_cars_2020_10_16_14-31-14/yolov3_final.weights --yolt_cfg_file /simrdwn/yolt3/cfg/yolov3.cfg --testims_dir /simrdwn/data --keep_test_slices 0 --test_slice_sep __ --test_make_legend_and_title 0 --edge_buffer_test 1 --test_box_rescale_frac 1 --plot_thresh_str 0.2 --slice_sizes_str 416 --slice_overlap 0.2 --alpha_scaling 1 --show_labels 1 --boxes_per_grid 9

I had met the similar question as you.When I start the test procedure and the procedure reminds me that FileNotFoundError: [Errno 2] No such file or directory '/home/xxx/simrdwn/results/test_yolt2_dense_class_label_2020_11_12_17-29-24/class_label.png'.I do not konw what happened.

**Comment by sunyuxiu** [comment]
@yunxiaozimeng I meet the same question as you!Do you have find out the reason?

**Comment by tnmygrwl** [comment]
I think the issue is when you update the args and construct `yolt_test_classes_files` then pass it to the `post_process. post_process_yolt_test_create_df`function. You can retrace the bug from [here](https://github.com/CosmiQ/simrdwn/blob/9f91eac5d0769400f89eefc145d67f0ee209d8fc/simrdwn/core/simrdwn.py#L295) probably.
